# Generated by Django 3.0 on 2020-05-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
